add reporting to rspec

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,6 +6,8 @@ on:
   push:
     branches:
       - main
+permissions:
+  checks: write
 env:
   TAG_COMMIT_PATH: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/use1-${{github.event.repository.name}}-ecr:${{github.run_attempt}}
 
@@ -38,10 +40,12 @@ jobs:
           echo $TAG_COMMIT_PATH
           docker build -t $TAG_COMMIT_PATH .
           docker push $TAG_COMMIT_PATH
+
   test:
+    # TODO: https://github.com/marketplace/actions/junit-report-action
     name: Test
     runs-on: ubuntu-latest
-    needs: [build]
+    needs: [ build ]
     env:
       DATABASE_NAME: journal_test
       DATABASE_HOST: localhost
@@ -61,13 +65,25 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
       - name: rspec
-        run: docker compose up rspec --quiet-pull
+        run: |
+          docker compose up rspec --quiet-pull
+          docker cp rspec:/rails_api/rspec.xml ..
+          docker compose down
+          cd ..
+          ls
+          pwd
+          # if grep -q 'failures="0"' rspec.xml; then echo no rspec errors; exit 0; else echo rspec errors; exit 1; fi
         working-directory: rails-api
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "rspec.xml"
   deploy-dev:
     name: Deploy to Dev
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request'
-    needs: [test]
+    needs: [ test ]
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
